Repository boxyhq/jackson, pull requests merged in 2023-10, with the labels that each got.

#1696 Docs: Update readme
  README.md
Labels: hacktoberfest

#1698 Removed all of these stars(✨)
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#1634 Skaffold Update
  kustomize/base/services/jackson-service.yaml
  kustomize/overlays/demo/.gitignore
  kustomize/overlays/demo/kustomization.yaml
  kustomize/overlays/demo/services/jackson-service.yaml
  kustomize/overlays/demo/services/kustomization.yaml
  kustomize/overlays/dynamodb/jackson-service.yaml
  kustomize/overlays/dynamodb/kustomization.yaml
  kustomize/overlays/mariadb/jackson-service.yaml
  kustomize/overlays/mariadb/kustomization.yaml
  kustomize/overlays/mongo/jackson-service.yaml
  kustomize/overlays/mongo/kustomization.yaml
  kustomize/overlays/mssql/jackson-service.yaml
  kustomize/overlays/mssql/kustomization.yaml
  kustomize/overlays/mysql/jackson-service.yaml
  kustomize/overlays/mysql/kustomization.yaml
  kustomize/overlays/postgres/jackson-service.yaml
  kustomize/overlays/postgres/kustomization.yaml
  package.json
  skaffold-demo-services.yaml
  skaffold-demo.yaml
  skaffold-dynamodb.yaml
  skaffold-mariadb.yaml
  skaffold-mongo.yaml
  skaffold-mssql.yaml
  skaffold-mysql.yaml
  skaffold-postgres.yaml
Labels: enhancement

#1766 CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted
