Repository boxyhq/jackson, pull requests merged in 2023-03, with the labels that each got.

#1000 Jumpcloud fixes
  npm/src/controller/connection/saml.ts
Labels: bug

#1017 Change casings for the styles property to match styled-jsx
  sdk/ui/react/src/Login/README.md
Labels: documentation

#1032 Using ORAS digest & beta tags in Github action
  .github/workflows/main.yml
Labels: enhancement
